
spring:
  application:
    name: demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/security?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
  # 如果字段值为null则不返回
#  jackson:
#    default-property-inclusion: non_null
  security:
    user:
      name: solo
      password: 123456
  session:
    store-type: none

  mvc:
    static-path-pattern: /**
server:
  port: 80

solo:
  security:
    browser:
#      loginPage: /demo-login.html
      loginType: JSON
      signUpUrl: /demo-signUp.html
    code:
      image:
        length: 4
        width: 100
        urls: /user
    social:
      qq:
        app-id: 101564623
        app-secret: 2cc99995cbf62f05fe2a6fda4771d7d4
        providerId: qq
      weixin:
        app-id: wxafb8ba47339d48be
        app-secret: ac9af4ee9dc8d41ad3f236ea55cf978b
        providerId: weixin
      filterProcessesUrl: /auth